/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { BatchPayload } from "../../BatchPayload";
import { Logger } from "winston";
import { fileDto } from "../../file.dto";
import * as XLSX from "xlsx";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { PatientSageFemmeMappingService } from "../patientSageFemmeMapping.service";
import { PatientSageFemmeMappingCreateInput } from "./PatientSageFemmeMappingCreateInput";
import { PatientSageFemmeMappingCreateManyInput } from "./PatientSageFemmeMappingCreateManyInput";
import { PatientSageFemmeMappingWhereInput } from "./PatientSageFemmeMappingWhereInput";
import { PatientSageFemmeMappingWhereUniqueInput } from "./PatientSageFemmeMappingWhereUniqueInput";
import { PatientSageFemmeMappingFindManyArgs } from "./PatientSageFemmeMappingFindManyArgs";
import { PatientSageFemmeMappingupdateManyArgs } from "./PatientSageFemmeMappingupdateManyArgs";
import { PatientSageFemmeMappingUpdateInput } from "./PatientSageFemmeMappingUpdateInput";
import { PatientSageFemmeMapping } from "./PatientSageFemmeMapping";
import { getListPatientSageFemmeMappingDto } from "./getListPatientSageFemmeMapping.dto";
@swagger.ApiBearerAuth()
export class PatientSageFemmeMappingControllerBase {
  constructor(
    protected readonly service: PatientSageFemmeMappingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder,
    protected readonly logger: Logger
  ) {}

  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: PatientSageFemmeMapping })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: PatientSageFemmeMappingCreateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<PatientSageFemmeMapping> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "PatientSageFemmeMapping",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      this.logger.log({
        level: "error",
        message: `providing the properties: ${properties} on ${"PatientSageFemmeMapping"} creation is forbidden for roles: ${roles}`,
      });

      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"PatientSageFemmeMapping"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: {
        ...data,

        patients: data.patients
          ? {
              connect: data.patients,
            }
          : undefined,

        sagesFemmes: data.sagesFemmes
          ? {
              connect: data.sagesFemmes,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,
        estSagefemmeReference: true,

        patients: {
          select: {
            id: true,
          },
        },

        sagesFemmes: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post("/createMany")
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: PatientSageFemmeMapping })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async createMany(
    @common.Body() data: Array<PatientSageFemmeMappingCreateManyInput>,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<BatchPayload | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "PatientSageFemmeMapping",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      this.logger.log({
        level: "error",
        message: `providing the properties: ${properties} on ${"PatientSageFemmeMapping"} creation is forbidden for roles: ${roles}`,
      });

      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"PatientSageFemmeMapping"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.createMany({
      data: data,
      skipDuplicates: false,
    });
  }

  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: getListPatientSageFemmeMappingDto })
  @swagger.ApiForbiddenResponse()
  @swagger.ApiQuery({
    type: () => PatientSageFemmeMappingFindManyArgs,
    style: "deepObject",
    explode: true,
  })
  async findMany(
    @common.Req() request: Request,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<PatientSageFemmeMapping>> {
    const args = plainToClass(
      PatientSageFemmeMappingFindManyArgs,
      request.query
    );

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "PatientSageFemmeMapping",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,
        estSagefemmeReference: true,

        patients: {
          select: {
            id: true,
          },
        },

        sagesFemmes: {
          select: {
            id: true,
          },
        },
      },
    });
    const result = results.paginatedResult.map(
      (result: PatientSageFemmeMapping) => permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/fileExcel")
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: fileDto })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findDataForExcel(
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<fileDto> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "PatientSageFemmeMapping",
    });
    const results = await this.service.findMany({
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,
        estSagefemmeReference: true,

        patients: {
          select: {
            id: true,
          },
        },

        sagesFemmes: {
          select: {
            id: true,
          },
        },
      },
    });
    const result = results.paginatedResult.map(
      (result: PatientSageFemmeMapping) => permission.filter(result)
    );
    var excelFile = XLSX.utils.json_to_sheet(result);

    var Workbook = XLSX.utils.book_new();
    await XLSX.utils.book_append_sheet(Workbook, excelFile, "test");
    const file = await XLSX.write(Workbook, {
      bookType: "xlsx",
      bookSST: true,
      type: "base64",
    });
    return { file: file };
  }

  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: PatientSageFemmeMapping })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: PatientSageFemmeMappingWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<PatientSageFemmeMapping | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "PatientSageFemmeMapping",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        deletedAt: true,
        estSagefemmeReference: true,

        patients: {
          select: {
            id: true,
          },
        },

        sagesFemmes: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      this.logger.log({
        level: "error",
        message: `No resource was found for ${JSON.stringify(params)}`,
      });
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: PatientSageFemmeMapping })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: PatientSageFemmeMappingWhereUniqueInput,
    @common.Body()
    data: PatientSageFemmeMappingUpdateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<PatientSageFemmeMapping | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "PatientSageFemmeMapping",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      this.logger.log({
        level: "error",
        message: `No resource was found for ${JSON.stringify(params)}`,
      });
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"PatientSageFemmeMapping"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          patients: data.patients
            ? {
                connect: data.patients,
              }
            : undefined,

          sagesFemmes: data.sagesFemmes
            ? {
                connect: data.sagesFemmes,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          deletedAt: true,
          estSagefemmeReference: true,

          patients: {
            select: {
              id: true,
            },
          },

          sagesFemmes: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        this.logger.log({
          level: "error",
          message: `No resource was found for ${JSON.stringify(params)}`,
        });
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: PatientSageFemmeMapping })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: PatientSageFemmeMappingWhereUniqueInput
  ): Promise<PatientSageFemmeMapping | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          deletedAt: true,
          estSagefemmeReference: true,

          patients: {
            select: {
              id: true,
            },
          },

          sagesFemmes: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        this.logger.log({
          level: "error",
          message: `No resource was found for ${JSON.stringify(params)}`,
        });
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
