/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { PatientSageFemmeMappingWhereInput } from "./PatientSageFemmeMappingWhereInput";
import { Type } from "class-transformer";

@ArgsType()
class PatientSageFemmeMappingupdateManyArgs {
  @ApiProperty({
    required: false,
    type: () => PatientSageFemmeMappingWhereInput,
  })
  @Field(() => PatientSageFemmeMappingWhereInput, { nullable: true })
  @Type(() => PatientSageFemmeMappingWhereInput)
  where?: PatientSageFemmeMappingWhereInput;
}

export { PatientSageFemmeMappingupdateManyArgs };
