/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { Logger } from "winston";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { CreatePatientSageFemmeMappingArgs } from "./CreatePatientSageFemmeMappingArgs";
import { UpdatePatientSageFemmeMappingArgs } from "./UpdatePatientSageFemmeMappingArgs";
import { DeletePatientSageFemmeMappingArgs } from "./DeletePatientSageFemmeMappingArgs";
import { PatientSageFemmeMappingFindManyArgs } from "./PatientSageFemmeMappingFindManyArgs";
import { PatientSageFemmeMappingFindUniqueArgs } from "./PatientSageFemmeMappingFindUniqueArgs";
import { PatientSageFemmeMapping } from "./PatientSageFemmeMapping";
import { Patient } from "../../patient/base/Patient";
import { SagesFemme } from "../../sagesFemme/base/SagesFemme";
import { PatientSageFemmeMappingService } from "../patientSageFemmeMapping.service";

@graphql.Resolver(() => PatientSageFemmeMapping)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PatientSageFemmeMappingResolverBase {
  constructor(
    protected readonly service: PatientSageFemmeMappingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder,
    protected readonly logger: Logger
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "read",
    possession: "any",
  })
  async _patientSageFemmeMappingsMeta(
    @graphql.Args() args: PatientSageFemmeMappingFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [PatientSageFemmeMapping])
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "read",
    possession: "any",
  })
  async patientSageFemmeMappings(
    @graphql.Args() args: PatientSageFemmeMappingFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<PatientSageFemmeMapping>> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "PatientSageFemmeMapping",
    });
    const results = await this.service.findMany(args);
    const result = results.paginatedResult.map(
      (result: PatientSageFemmeMapping) => permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @graphql.Query(() => PatientSageFemmeMapping, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "read",
    possession: "own",
  })
  async patientSageFemmeMapping(
    @graphql.Args() args: PatientSageFemmeMappingFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PatientSageFemmeMapping | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "PatientSageFemmeMapping",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => PatientSageFemmeMapping)
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "create",
    possession: "any",
  })
  async createPatientSageFemmeMapping(
    @graphql.Args() args: CreatePatientSageFemmeMappingArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PatientSageFemmeMapping> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "PatientSageFemmeMapping",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"PatientSageFemmeMapping"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        patients: args.data.patients
          ? {
              connect: args.data.patients,
            }
          : undefined,

        sagesFemmes: args.data.sagesFemmes
          ? {
              connect: args.data.sagesFemmes,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => PatientSageFemmeMapping)
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "update",
    possession: "any",
  })
  async updatePatientSageFemmeMapping(
    @graphql.Args() args: UpdatePatientSageFemmeMappingArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PatientSageFemmeMapping | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "PatientSageFemmeMapping",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"PatientSageFemmeMapping"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          patients: args.data.patients
            ? {
                connect: args.data.patients,
              }
            : undefined,

          sagesFemmes: args.data.sagesFemmes
            ? {
                connect: args.data.sagesFemmes,
              }
            : undefined,
        },
      });
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PatientSageFemmeMapping)
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "delete",
    possession: "any",
  })
  async deletePatientSageFemmeMapping(
    @graphql.Args() args: DeletePatientSageFemmeMappingArgs
  ): Promise<PatientSageFemmeMapping | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Patient, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "read",
    possession: "any",
  })
  async patients(
    @graphql.Parent() parent: PatientSageFemmeMapping,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Patient | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Patient",
    });
    const result = await this.service.getPatients(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => SagesFemme, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PatientSageFemmeMapping",
    action: "read",
    possession: "any",
  })
  async sagesFemmes(
    @graphql.Parent() parent: PatientSageFemmeMapping,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SagesFemme | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "SagesFemme",
    });
    const result = await this.service.getSagesFemmes(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
