/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { PatientSageFemmeMappingWhereInput } from "./PatientSageFemmeMappingWhereInput";
import { Type } from "class-transformer";
import { PatientSageFemmeMappingOrderByInput } from "./PatientSageFemmeMappingOrderByInput";

@ArgsType()
class PatientSageFemmeMappingFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => PatientSageFemmeMappingWhereInput,
  })
  @Field(() => PatientSageFemmeMappingWhereInput, { nullable: true })
  @Type(() => PatientSageFemmeMappingWhereInput)
  where?: PatientSageFemmeMappingWhereInput;

  @ApiProperty({
    required: false,
    type: PatientSageFemmeMappingOrderByInput,
  })
  @Field(() => PatientSageFemmeMappingOrderByInput, { nullable: true })
  @Type(() => PatientSageFemmeMappingOrderByInput)
  orderBy?: PatientSageFemmeMappingOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { PatientSageFemmeMappingFindManyArgs };
