/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { Logger } from "winston";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { CreateSagesFemmeArgs } from "./CreateSagesFemmeArgs";
import { UpdateSagesFemmeArgs } from "./UpdateSagesFemmeArgs";
import { DeleteSagesFemmeArgs } from "./DeleteSagesFemmeArgs";
import { SagesFemmeFindManyArgs } from "./SagesFemmeFindManyArgs";
import { SagesFemmeFindUniqueArgs } from "./SagesFemmeFindUniqueArgs";
import { SagesFemme } from "./SagesFemme";
import { CreneauxConsultationDomicileFindManyArgs } from "../../creneauxConsultationDomicile/base/CreneauxConsultationDomicileFindManyArgs";
import { CreneauxConsultationDomicile } from "../../creneauxConsultationDomicile/base/CreneauxConsultationDomicile";
import { PatientSageFemmeMappingFindManyArgs } from "../../patientSageFemmeMapping/base/PatientSageFemmeMappingFindManyArgs";
import { PatientSageFemmeMapping } from "../../patientSageFemmeMapping/base/PatientSageFemmeMapping";
import { PatientFindManyArgs } from "../../patient/base/PatientFindManyArgs";
import { Patient } from "../../patient/base/Patient";
import { Room } from "../../room/base/Room";
import { User } from "../../user/base/User";
import { SagesFemmeService } from "../sagesFemme.service";

@graphql.Resolver(() => SagesFemme)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SagesFemmeResolverBase {
  constructor(
    protected readonly service: SagesFemmeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder,
    protected readonly logger: Logger
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SagesFemme",
    action: "read",
    possession: "any",
  })
  async _sagesFemmesMeta(
    @graphql.Args() args: SagesFemmeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [SagesFemme])
  @nestAccessControl.UseRoles({
    resource: "SagesFemme",
    action: "read",
    possession: "any",
  })
  async sagesFemmes(
    @graphql.Args() args: SagesFemmeFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<SagesFemme>> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "SagesFemme",
    });
    const results = await this.service.findMany(args);
    const result = results.paginatedResult.map((result: SagesFemme) =>
      permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @graphql.Query(() => SagesFemme, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SagesFemme",
    action: "read",
    possession: "own",
  })
  async sagesFemme(
    @graphql.Args() args: SagesFemmeFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SagesFemme | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "SagesFemme",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => SagesFemme)
  @nestAccessControl.UseRoles({
    resource: "SagesFemme",
    action: "create",
    possession: "any",
  })
  async createSagesFemme(
    @graphql.Args() args: CreateSagesFemmeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SagesFemme> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "SagesFemme",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SagesFemme"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        room: args.data.room
          ? {
              connect: args.data.room,
            }
          : undefined,

        users: args.data.users
          ? {
              connect: args.data.users,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => SagesFemme)
  @nestAccessControl.UseRoles({
    resource: "SagesFemme",
    action: "update",
    possession: "any",
  })
  async updateSagesFemme(
    @graphql.Args() args: UpdateSagesFemmeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SagesFemme | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "SagesFemme",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SagesFemme"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          room: args.data.room
            ? {
                connect: args.data.room,
              }
            : undefined,

          users: args.data.users
            ? {
                connect: args.data.users,
              }
            : undefined,
        },
      });
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SagesFemme)
  @nestAccessControl.UseRoles({
    resource: "SagesFemme",
    action: "delete",
    possession: "any",
  })
  async deleteSagesFemme(
    @graphql.Args() args: DeleteSagesFemmeArgs
  ): Promise<SagesFemme | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error: any) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [CreneauxConsultationDomicile])
  @nestAccessControl.UseRoles({
    resource: "SagesFemme",
    action: "read",
    possession: "any",
  })
  async creneauxConsultationDomicile(
    @graphql.Parent() parent: SagesFemme,
    @graphql.Args() args: CreneauxConsultationDomicileFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CreneauxConsultationDomicile[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "CreneauxConsultationDomicile",
    });
    const results = await this.service.findCreneauxConsultationDomicile(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [PatientSageFemmeMapping])
  @nestAccessControl.UseRoles({
    resource: "SagesFemme",
    action: "read",
    possession: "any",
  })
  async patientSageFemmeMapping(
    @graphql.Parent() parent: SagesFemme,
    @graphql.Args() args: PatientSageFemmeMappingFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PatientSageFemmeMapping[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "PatientSageFemmeMapping",
    });
    const results = await this.service.findPatientSageFemmeMapping(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [Patient])
  @nestAccessControl.UseRoles({
    resource: "SagesFemme",
    action: "read",
    possession: "any",
  })
  async patient(
    @graphql.Parent() parent: SagesFemme,
    @graphql.Args() args: PatientFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Patient[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Patient",
    });
    const results = await this.service.findPatient(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Room, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SagesFemme",
    action: "read",
    possession: "any",
  })
  async room(
    @graphql.Parent() parent: SagesFemme,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Room | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Room",
    });
    const result = await this.service.getRoom(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SagesFemme",
    action: "read",
    possession: "any",
  })
  async users(
    @graphql.Parent() parent: SagesFemme,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUsers(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
